### PR TITLE
Use googletest as a submodule + Support for CTest + IDE Support

### PR DESCRIPTION
**Pull request by xorz57**
## Submodules
- Added `googletest` as a git submodule.
- Removed *downloaded* `googletest` directory

## CMake
- Added comments inside top-level CMakeLists.txt for readability.
- Added googletest library.
- Added support for ctest so that you just run one command instead of running all tests by your self***.
- Added 2 *optional* CMake macros to add tests without typing the same commands everytime.

# Demonstration of how CTest can be helpful***

```sh
mkdir build
cd build
make -j2
ctest
```

image

After ctest executes it will "grab" all registered tests and run them.

#### Small note for those using git

Because we are using submodules to get our dependencies, the user should now how to clone the submodules.

Here are 3 ways to do it.

- Use a GUI git tool (GUI tools will probably ask you if you want to clone the submodules)

- Clone the project with all its submodules (1 step)
```sh
git clone --recurse-submodules https://github.com/JLospinoso/ccc
```

- Clone the project and then update and init all submodules (2 steps)
```sh
git clone https://github.com/JLospinoso/ccc
git submodule update --init --recursive
```

Done! You are ready to start compiling :smiley:

### CODE REVIEW

**Comment by xorz57** [comment]
Fact: CTest is also supported on Visual Studio 2017 and 2019. This means that you can run the tests from the GUI as well.

**Comment by xorz57** [comment]
I want to make some more changes to make things as good as possible.

**Comment by xorz57** [comment]
@JLospinoso It's ready!

**Comment by JLospinoso** [comment]
@xorz57 Great work, thanks again!

**Pull request merged**
